version: 2
updates:
    - package-ecosystem: composer
      directory: "/"
      schedule:
          interval: monthly
      versioning-strategy: increase

    - package-ecosystem: composer
      directory: "/"
      schedule:
        interval: monthly
      versioning-strategy: increase
      target-branch: "7.4"