version: 2
updates:
    - package-ecosystem: composer
      directory: "/"
      schedule:
          interval: monthly
      versioning-strategy: increase

    - package-ecosystem: composer
      directory: "/"
      schedule:
        interval: monthly
      ignore:
        - dependency-name: "slim/slim"
          versions: ["^3.0", "^4.0"]
      versioning-strategy: increase
      target-branch: "7.4"
